# Generated by Django 5.0 on 2025-02-24 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+380XXXXXXXXX' (total 13 characters).", regex='^\\+380\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_img_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
